<?xml version="1.0" encoding="utf-8"?><Database Name="CrossfitTracker" Class="CrossFitTrackerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-0AH4JG6\SQLSERVER2019;Initial Catalog=CrossfitTracker;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CrossFitConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.Countries_Insert" Method="Countries_Insert">
    <Parameter Name="CountryCode" Parameter="countryCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CountryDescription" Parameter="countryDescription" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Countries_Update" Method="Countries_Update">
    <Parameter Name="CountryID" Parameter="countryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CountryCode" Parameter="countryCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CountryDescription" Parameter="countryDescription" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Countries_ViewAll" Method="Countries_ViewAll">
    <ElementType Name="Countries_ViewAllResult">
      <Column Name="CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountryCode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="CountryDescription" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DiaryEntries_Insert" Method="DiaryEntries_Insert">
    <Parameter Name="DiaryEntryTitle" Parameter="diaryEntryTitle" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DiaryEntry" Parameter="diaryEntry" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DiaryEntries_SingleRecord" Method="DiaryEntries_SingleRecord">
    <Parameter Name="DiaryEntryID" Parameter="diaryEntryID" Type="System.Int32" DbType="Int" />
    <ElementType Name="DiaryEntries_SingleRecordResult">
      <Column Name="DiaryEntryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiaryEntryTitle" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaryEntry" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageSource1" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ImageSource2" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ImageSource3" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DiaryEntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DiaryEntries_Update" Method="DiaryEntries_Update">
    <Parameter Name="DiaryEntryID" Parameter="diaryEntryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DiaryEntryTitle" Parameter="diaryEntryTitle" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DiaryEntry" Parameter="diaryEntry" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ImageSource1" Parameter="imageSource1" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ImageSource2" Parameter="imageSource2" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ImageSource3" Parameter="imageSource3" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DiaryEntries_ViewAll" Method="DiaryEntries_ViewAll">
    <ElementType Name="DiaryEntries_ViewAllResult">
      <Column Name="DiaryEntryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiaryEntryTitle" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaryEntry" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageSource1" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ImageSource2" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ImageSource3" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DiaryEntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>