<?xml version="1.0" encoding="utf-8"?><Database Name="CrossfitTracker" Class="CrossFitTrackerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-0AH4JG6\SQLSERVER2019;Initial Catalog=CrossfitTracker;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CrossFitConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.Countries_Insert" Method="Countries_Insert">
    <Parameter Name="CountryCode" Parameter="countryCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CountryDescription" Parameter="countryDescription" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Countries_Update" Method="Countries_Update">
    <Parameter Name="CountryID" Parameter="countryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CountryCode" Parameter="countryCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CountryDescription" Parameter="countryDescription" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Countries_ViewAll" Method="Countries_ViewAll">
    <ElementType Name="Countries_ViewAllResult">
      <Column Name="CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountryCode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="CountryDescription" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DiaryEntries_Insert" Method="DiaryEntries_Insert">
    <Parameter Name="DiaryEntryTitle" Parameter="diaryEntryTitle" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DiaryEntry" Parameter="diaryEntry" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DiaryEntries_SingleRecord" Method="DiaryEntries_SingleRecord">
    <Parameter Name="DiaryEntryID" Parameter="diaryEntryID" Type="System.Int32" DbType="Int" />
    <ElementType Name="DiaryEntries_SingleRecordResult">
      <Column Name="DiaryEntryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiaryEntryTitle" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaryEntry" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageSource1" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ImageSource2" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ImageSource3" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DiaryEntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DiaryEntries_Update" Method="DiaryEntries_Update">
    <Parameter Name="DiaryEntryID" Parameter="diaryEntryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DiaryEntryTitle" Parameter="diaryEntryTitle" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DiaryEntry" Parameter="diaryEntry" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ImageSource1" Parameter="imageSource1" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ImageSource2" Parameter="imageSource2" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ImageSource3" Parameter="imageSource3" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DiaryEntries_ViewAll" Method="DiaryEntries_ViewAll">
    <ElementType Name="DiaryEntries_ViewAllResult">
      <Column Name="DiaryEntryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiaryEntryTitle" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaryEntry" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageSource1" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ImageSource2" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ImageSource3" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DiaryEntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AdaptiveOptions_Insert" Method="AdaptiveOptions_Insert">
    <Parameter Name="AdaptiveOption" Parameter="adaptiveOption" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AdaptiveOptions_Update" Method="AdaptiveOptions_Update">
    <Parameter Name="AdaptiveOptionID" Parameter="adaptiveOptionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdaptiveOption" Parameter="adaptiveOption" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AdaptiveOptions_ViewAll" Method="AdaptiveOptions_ViewAll">
    <ElementType Name="AdaptiveOptions_ViewAllResult">
      <Column Name="AdaptiveOptionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdaptiveOption" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Divisions_ViewAll" Method="Divisions_ViewAll">
    <ElementType Name="Divisions_ViewAllResult">
      <Column Name="DivisionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DivisionName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Divisions_Insert" Method="Divisions_Insert">
    <Parameter Name="DivisionName" Parameter="divisionName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Divisions_Update" Method="Divisions_Update">
    <Parameter Name="DivisionID" Parameter="divisionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DivisionName" Parameter="divisionName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExerciseAreas_Insert" Method="ExerciseAreas_Insert">
    <Parameter Name="ExerciseAreaDescription" Parameter="exerciseAreaDescription" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExerciseAreas_Update" Method="ExerciseAreas_Update">
    <Parameter Name="ExerciseBodyAreaID" Parameter="exerciseBodyAreaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ExerciseAreaDescription" Parameter="exerciseAreaDescription" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExerciseAreas_ViewAll" Method="ExerciseAreas_ViewAll">
    <ElementType Name="ExerciseAreas_ViewAllResult">
      <Column Name="ExerciseBodyAreaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExerciseAreaDescription" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.EventNumbers_Insert" Method="EventNumbers_Insert">
    <Parameter Name="EventNumberDescription" Parameter="eventNumberDescription" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EventNumbers_Update" Method="EventNumbers_Update">
    <Parameter Name="EventNumberID" Parameter="eventNumberID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EventNumberDescription" Parameter="eventNumberDescription" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EventNumbers_ViewAll" Method="EventNumbers_ViewAll">
    <ElementType Name="EventNumbers_ViewAllResult">
      <Column Name="EventNumberID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventNumberDescription" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Scales_Insert" Method="Scales_Insert">
    <Parameter Name="ScaleDescription" Parameter="scaleDescription" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Scales_ViewAll" Method="Scales_ViewAll">
    <ElementType Name="Scales_ViewAllResult">
      <Column Name="ScaleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScaleDescription" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Scales_Update" Method="Scales_Update">
    <Parameter Name="ScaleID" Parameter="scaleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ScaleDescription" Parameter="scaleDescription" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Exercises_Insert" Method="Exercises_Insert">
    <Parameter Name="Exercise" Parameter="exercise" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ExerciseDescription" Parameter="exerciseDescription" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Exercises_Update" Method="Exercises_Update">
    <Parameter Name="ExerciseID" Parameter="exerciseID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Exercise" Parameter="exercise" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ExerciseDescription" Parameter="exerciseDescription" Type="System.String" DbType="VarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Exercises_ViewAll" Method="Exercises_ViewAll">
    <ElementType Name="Exercises_ViewAllResult">
      <Column Name="ExerciseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExerciseBodyAreaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Exercise" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExerciseDescription" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ExerciseAreaDescription" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>